### PR TITLE
Fix speaker notes window

### PR DESCRIPTION
**Pull request by justahero**
This fixes the speaker notes popup window, where timer, next slides and the notes of the currently open slide are displayed.

Before this change the speaker notes window reported an "Invalid file type" error only.

* update Ruby gem [asciidoctor-revealjs](https://github.com/asciidoctor/asciidoctor-reveal.js) to latest version
* set different `reveal.js` version in `Rakefile` as directory to fetch data from

(updated description)

### CODE REVIEW

**Comment by amanjeev** [comment]
@justahero  - Am I doing something wrong? My steps are - 

1. Checkout your branch
2. run `./rake`
3. run local web server `python3 -m http.server`
4. visit http://localhost:8000/target/compound-types.html#/_construction
5. press `S`
I see popup but notes.html returns 404.

**Comment by amanjeev** [comment]
This is so strange indeed. Neither opening the file as you showed, nor with the a local web server it works for me.  But the slide always loads, just the popup says 404.

We do not deploy this on a canary or something?

**Comment by justahero** [comment]
Ok, fortunately I was able to replicate your observed behaviour on a different machine & can hopefully provide a fix now that works for everyone. I updated the Ruby gem `asciidoctor-revealjs` version to the most recent one, `5.0.0-rc1`, which also allows us to bump the underlying `reveal.js` version (to the recent `4.3.1`).

The speaker notes popup window should work now, **note** the URL is not pointing to a non-existent file (`/plugin/notes/notes.html`) anymore, but rather has the same URL as the presentation. Personally the slides now look as intended, but due to the version bump I suggest to check the slides again, I might have easily missed something that is now different or even broken.

Using

```console
bundle install
rake
python3 -m http.server
```

should update the project. Please let me know if that works for you. :)

**Review by amanjeev — APPROVED** [review]
Love it! Thank you!

**Comment by amanjeev** [comment]
Shall we merge this?

**Pull request merged**
