### PR TITLE
gitignore: ignore generated html files

### PR DESCRIPTION
**Pull request by Lotterleben**
add generated html files to `.gitignore` to make `git status` output less... overly verbose

### CODE REVIEW

**Comment by matklad** [comment]
Will this affect gh-pages?

**Comment by Lotterleben** [comment]
Good question, I have no idea...

**Comment by skade** [comment]
AFAIK, it doesn't. You may just try and see if it breaks ;).

**Comment by Lotterleben** [comment]
yolo-driven documenting :D

**Comment by skade** [comment]
@Lotterleben Fixed!

**Comment by Lotterleben** [comment]
Okay! here we go 🚀

**Pull request merged**
